print("мы будем строить башню!")
print("первая переменная высота(измеряется в блоках")
h = int(input("введите высоту башни в блоках от '0' до '23'"))
while h>23 or h<0:
    h = int(input("введите высоту башни в блоках от '0' до '23'"))
probel = " "
blok = "#"
if h >= 0 and h <= 23:
    if h == 0:
        print(2 * probel)
    elif h == 1:
        print(1 * probel + 2 * probel)
        print(2 * blok)
    elif h == 2:
        print(2 * probel + 2 * probel)
        print(1 * probel + 2 * blok)
        print(4 * blok)
    elif h == 3:
        print(3 * probel + 2 * probel)
        print(2 * probel + 2 * blok)
        print(1 * probel + 4 * blok)
        print(6 * blok)
    elif h == 4:
        print(4 * probel + 2 * probel)
        print(3 * probel + 2 * blok)
        print(2 * probel + 4 * blok)
        print(1 * probel + 6 * blok)
        print(8 * blok)
    elif h == 5:
        print(5 * probel + 2 * probel)
        print(4 * probel + 2 * blok)
        print(3 * probel + 4 * blok)
        print(2 * probel + 6 * blok)
        print(1 * probel + 8 * blok)
        print(10 * blok)
    elif h == 6:
        print(6 * probel + 2 * probel)
        print(5 * probel + 2 * blok)
        print(4 * probel + 4 * blok)
        print(3 * probel + 6 * blok)
        print(2 * probel + 8 * blok)
        print(1 * probel + 10 * blok)
        print(12 * blok)
    elif h == 7:
        print(7 * probel + 2 * probel)
        print(6 * probel + 2 * blok)
        print(5 * probel + 4 * blok)
        print(4 * probel + 6 * blok)
        print(3 * probel + 8 * blok)
        print(2 * probel + 10 * blok)
        print(1 * probel + 12 * blok)
        print(14 * blok)
    elif h == 8:
        print(8 * probel + 2 * probel)
        print(7 * probel + 2 * blok)
        print(6 * probel + 4 * blok)
        print(5 * probel + 6 * blok)
        print(4 * probel + 8 * blok)
        print(3 * probel + 10 * blok)
        print(2 * probel + 12 * blok)
        print(1 * probel + 14 * blok)
        print(16 * blok)
    elif h == 9:
        print(9 * probel + 2 * probel)
        print(8 * probel + 2 * blok)
        print(7 * probel + 4 * blok)
        print(6 * probel + 6 * blok)
        print(5 * probel + 8 * blok)
        print(4 * probel + 10 * blok)
        print(3 * probel + 12 * blok)
        print(2 * probel + 14 * blok)
        print(1 * probel + 16 * blok)
        print(18 * blok)
    elif h == 10:
        print(10 * probel + 2 * probel)
        print(9 * probel + 2 * blok)
        print(8 * probel + 4 * blok)
        print(7 * probel + 6 * blok)
        print(6 * probel + 8 * blok)
        print(5 * probel + 10 * blok)
        print(4 * probel + 12 * blok)
        print(3 * probel + 14 * blok)
        print(2 * probel + 16 * blok)
        print(1 * probel + 18 * blok)
        print(20 * blok)
    elif h == 11:
        print(11 * probel + 2 * probel)
        print(10 * probel + 2 * blok)
        print(9 * probel + 4 * blok)
        print(8 * probel + 6 * blok)
        print(7 * probel + 8 * blok)
        print(6 * probel + 10 * blok)
        print(5 * probel + 12 * blok)
        print(4 * probel + 14 * blok)
        print(3 * probel + 16 * blok)
        print(2 * probel + 18 * blok)
        print(1 * probel + 20 * blok)
        print(22 * blok)
    elif h == 12:
        print(12 * probel + 2 * probel)
        print(11 * probel + 2 * blok)
        print(10 * probel + 4 * blok)
        print(9 * probel + 6 * blok)
        print(8 * probel + 8 * blok)
        print(7 * probel + 10 * blok)
        print(6 * probel + 12 * blok)
        print(5 * probel + 14 * blok)
        print(4 * probel + 16 * blok)
        print(3 * probel + 18 * blok)
        print(2 * probel + 20 * blok)
        print(1 * probel + 22 * blok)
        print(24 * blok)
    elif h == 13:
        print(13 * probel + 2 * probel)
        print(12 * probel + 2 * blok)
        print(11 * probel + 4 * blok)
        print(10 * probel + 6 * blok)
        print(9 * probel + 8 * blok)
        print(8 * probel + 10 * blok)
        print(7 * probel + 12 * blok)
        print(6 * probel + 14 * blok)
        print(5 * probel + 16 * blok)
        print(4 * probel + 18 * blok)
        print(3 * probel + 20 * blok)
        print(2 * probel + 22 * blok)
        print(1 * probel + 24 * blok)
        print(26 * blok)
    elif h == 14:
        print(14 * probel + 2 * probel)
        print(13 * probel + 2 * blok)
        print(12 * probel + 4 * blok)
        print(11 * probel + 6 * blok)
        print(10 * probel + 8 * blok)
        print(9 * probel + 10 * blok)
        print(8 * probel + 12 * blok)
        print(7 * probel + 14 * blok)
        print(6 * probel + 16 * blok)
        print(5 * probel + 18 * blok)
        print(4 * probel + 20 * blok)
        print(3 * probel + 22 * blok)
        print(2 * probel + 24 * blok)
        print(1 * probel + 26 * blok)
        print(28 * blok)
    elif h == 15:
        print(15 * probel + 2 * probel)
        print(14 * probel + 2 * blok)
        print(13 * probel + 4 * blok)
        print(12 * probel + 6 * blok)
        print(11 * probel + 8 * blok)
        print(10 * probel + 10 * blok)
        print(9 * probel + 12 * blok)
        print(8 * probel + 14 * blok)
        print(7 * probel + 16 * blok)
        print(6 * probel + 18 * blok)
        print(5 * probel + 20 * blok)
        print(4 * probel + 22 * blok)
        print(3 * probel + 24 * blok)
        print(2 * probel + 26 * blok)
        print(1 * probel + 28 * blok)
        print(30 * blok)
    elif h == 16:
        print(16 * probel + 2 * probel)
        print(15 * probel + 2 * blok)
        print(14 * probel + 4 * blok)
        print(13 * probel + 6 * blok)
        print(12 * probel + 8 * blok)
        print(11 * probel + 10 * blok)
        print(10 * probel + 12 * blok)
        print(9 * probel + 14 * blok)
        print(8 * probel + 16 * blok)
        print(7 * probel + 18 * blok)
        print(6 * probel + 20 * blok)
        print(5 * probel + 22 * blok)
        print(4 * probel + 24 * blok)
        print(3 * probel + 26 * blok)
        print(2 * probel + 28 * blok)
        print(1 * probel + 30 * blok)
        print(32 * blok)
    elif h == 17:
        print(17 * probel + 2 * probel)
        print(16 * probel + 2 * blok)
        print(15 * probel + 4 * blok)
        print(14 * probel + 6 * blok)
        print(13 * probel + 8 * blok)
        print(12 * probel + 10 * blok)
        print(11 * probel + 12 * blok)
        print(10 * probel + 14 * blok)
        print(9 * probel + 16 * blok)
        print(8 * probel + 18 * blok)
        print(7 * probel + 20 * blok)
        print(6 * probel + 22 * blok)
        print(5 * probel + 24 * blok)
        print(4 * probel + 26 * blok)
        print(3 * probel + 28 * blok)
        print(2 * probel + 30 * blok)
        print(1 * probel + 32 * blok)
        print(34 * blok)
    elif h == 18:
        print(18 * probel + 2 * probel)
        print(17 * probel + 2 * blok)
        print(16 * probel + 4 * blok)
        print(15 * probel + 6 * blok)
        print(14 * probel + 8 * blok)
        print(13 * probel + 10 * blok)
        print(12 * probel + 12 * blok)
        print(11 * probel + 14 * blok)
        print(10 * probel + 16 * blok)
        print(9 * probel + 18 * blok)
        print(8 * probel + 20 * blok)
        print(7 * probel + 22 * blok)
        print(6 * probel + 24 * blok)
        print(5 * probel + 26 * blok)
        print(4 * probel + 28 * blok)
        print(3 * probel + 30 * blok)
        print(2 * probel + 32 * blok)
        print(1 * probel + 34 * blok)
        print(36 * blok)
    elif h == 19:
        print(19 * probel + 2 * probel)
        print(18 * probel + 2 * blok)
        print(17 * probel + 4 * blok)
        print(16 * probel + 6 * blok)
        print(15 * probel + 8 * blok)
        print(14 * probel + 10 * blok)
        print(13 * probel + 12 * blok)
        print(12 * probel + 14 * blok)
        print(11 * probel + 16 * blok)
        print(10 * probel + 18 * blok)
        print(9 * probel + 20 * blok)
        print(8 * probel + 22 * blok)
        print(7 * probel + 24 * blok)
        print(6 * probel + 26 * blok)
        print(5 * probel + 28 * blok)
        print(4* probel + 30 * blok)
        print(3* probel + 32 * blok)
        print(2 * probel + 34 * blok)
        print(1 * probel + 36 * blok)
        print(38 * blok)
    elif h == 20:
        print(20 * probel + 2 * probel)
        print(19 * probel + 2 * blok)
        print(18 * probel + 4 * blok)
        print(17 * probel + 6 * blok)
        print(16 * probel + 8 * blok)
        print(15 * probel + 10 * blok)
        print(14 * probel + 12 * blok)
        print(13 * probel + 14 * blok)
        print(12 * probel + 16 * blok)
        print(11 * probel + 18 * blok)
        print(10 * probel + 20 * blok)
        print(9 * probel + 22 * blok)
        print(8 * probel + 24 * blok)
        print(7 * probel + 26 * blok)
        print(6 * probel + 28 * blok)
        print(5 * probel + 30 * blok)
        print(4 * probel + 32 * blok)
        print(3 * probel + 34 * blok)
        print(2 * probel + 36 * blok)
        print(1 * probel + 38 * blok)
        print(40 * blok)
    elif h == 21:
        print(21 * probel + 2 * probel)
        print(20 * probel + 2 * blok)
        print(19 * probel + 4 * blok)
        print(18 * probel + 6 * blok)
        print(17 * probel + 8 * blok)
        print(16 * probel + 10 * blok)
        print(15 * probel + 12 * blok)
        print(14 * probel + 14 * blok)
        print(13 * probel + 16 * blok)
        print(12 * probel + 18 * blok)
        print(11 * probel + 20 * blok)
        print(10 * probel + 22 * blok)
        print(9 * probel + 24 * blok)
        print(8 * probel + 26 * blok)
        print(7 * probel + 28 * blok)
        print(6 * probel + 30 * blok)
        print(5 * probel + 32 * blok)
        print(4 * probel + 34 * blok)
        print(3 * probel + 36 * blok)
        print(2 * probel + 38 * blok)
        print(1 * probel + 40 * blok)
        print(42 * blok)
    elif h == 22:
        print(22 * probel + 2 * probel)
        print(21 * probel + 2 * blok)
        print(20 * probel + 4 * blok)
        print(19 * probel + 6 * blok)
        print(18 * probel + 8 * blok)
        print(17 * probel + 10 * blok)
        print(16 * probel + 12 * blok)
        print(15 * probel + 14 * blok)
        print(14 * probel + 16 * blok)
        print(13 * probel + 18 * blok)
        print(12 * probel + 20 * blok)
        print(11 * probel + 22 * blok)
        print(10 * probel + 24 * blok)
        print(9 * probel + 26 * blok)
        print(8 * probel + 28 * blok)
        print(7 * probel + 30 * blok)
        print(6 * probel + 32 * blok)
        print(5 * probel + 34 * blok)
        print(4 * probel + 36 * blok)
        print(3 * probel + 38 * blok)
        print(2 * probel + 40 * blok)
        print(1 * probel + 42 * blok)
        print(44 * blok)
    elif h == 23:
        print(23 * probel + 2 * probel)
        print(22 * probel + 2 * blok)
        print(21 * probel + 4 * blok)
        print(20 * probel + 6 * blok)
        print(19 * probel + 8 * blok)
        print(18 * probel + 10 * blok)
        print(17 * probel + 12 * blok)
        print(16 * probel + 14 * blok)
        print(15 * probel + 16 * blok)
        print(14 * probel + 18 * blok)
        print(13 * probel + 20 * blok)
        print(12 * probel + 22 * blok)
        print(11 * probel + 24 * blok)
        print(10 * probel + 26 * blok)
        print(9 * probel + 28 * blok)
        print(8 * probel + 30 * blok)
        print(7 * probel + 32 * blok)
        print(6 * probel + 34 * blok)
        print(5 * probel + 36 * blok)
        print(4 * probel + 38 * blok)
        print(3 * probel + 40 * blok)
        print(2 * probel + 42 * blok)
        print(1 * probel + 44 * blok)
        print(46 * blok)

else:
    print("введите целую величину удовлетворяющую отрезку от 0 до 23")
